ignore:
  - "src/pages"
  - "src/components"
  - "src/icons"
  - "src/stylesheets"
  - "src/utils/server.js"
  - "index.js"
  - "index.css"
  - "logo.svg"
  - "App.css"
  - "App.js"
  - "src/App.js"
  - "src/index.js"
  - "src/utils/userDetails.js"
  - "src/utils/rating.js"
  - "src/utils/database_functions.js"
