# sample regex patterns
ignore:
  - "src/components"  # ignore folders and all its contents
  - "src/pages"
  - "src/stylesheets"
  - "src/icons"
  - "App.js"
  - "index.css"
  - "index.js"
  - "logo.svg"
